#! /bin/bash

#SBATCH -J pcse2016lychrel
#SBATCH -A PCSE-2016 
#SBATCH -n 2
#SBATCH --ntasks-per-node=1
#SBATCH -p normal
#SBATCH -t 01:00:00 
#SBATCH --error=lychrel%J.err
#SBATCH --output=lychrel%J.out

echo "starting at `date`"
echo "running on hosts: $SLURM_NODELIST"
echo "running on $SLURM_NODES nodes"
echo "running on $SLURM_NPROCS procs"
echo "working dir: `pwd`"
ibrun ./findchain 100000000000000000000
# note that is is 21 digits long
echo "program completed. exit code: $? at: `date`"
