#! /bin/bash

#SBATCH -J pcse2016lychrel
#SBATCH -A PCSE-2016 
#SBATCH -n 32
#SBATCH --ntasks-per-node=16
#SBATCH -p normal
#SBATCH -t 00:15:00 
#SBATCH --error=lychrel%J.err
#SBATCH --output=lychrel%J.out

echo "starting at `date`"
echo "running on hosts: $SLURM_NODELIST"
echo "running on $SLURM_NODES nodes"
echo "running on $SLURM_NPROCS procs"
echo "working dir: `pwd`"
ibrun ./findchain 12
echo "program completed. exit code: $? at: `date`"
